/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffb2b9",
        "on-tertiary-fixed-variant": "#6f1042",
        "on-secondary-container": "#f1f9ff",
        "on-background": "#e5e4ed",
        tertiary: "#ff9ac2",
        primary: "#b1a1ff",
        "on-primary-fixed": "#000000",
        "primary-fixed": "#a491ff",
        "primary-fixed-dim": "#9780ff",
        "secondary-fixed-dim": "#70ceff",
        "surface-container-highest": "#23262e",
        error: "#ff6e84",
        "on-primary-container": "#230075",
        "surface-variant": "#23262e",
        "on-surface-variant": "#aaaab3",
        "on-tertiary-container": "#5c0034",
        "on-secondary": "#00374c",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "surface-tint": "#b1a1ff",
        "on-tertiary": "#6b0c3f",
        "tertiary-fixed": "#ff8cbb",
        "secondary-dim": "#00b2ed",
        "surface-container": "#171921",
        "tertiary-fixed-dim": "#f37cae",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#ec77a9",
        "inverse-primary": "#613de3",
        "on-secondary-fixed-variant": "#005776",
        "secondary-fixed": "#9adaff",
        "primary-dim": "#7757fa",
        "on-tertiary-fixed": "#37001d",
        "on-secondary-fixed": "#00394e",
        "surface-dim": "#0c0e14",
        "on-primary": "#2f0095",
        outline: "#74757d",
        surface: "#0c0e14",
        "error-container": "#a70138",
        "inverse-on-surface": "#53555c",
        "surface-bright": "#292c35",
        "on-primary-fixed-variant": "#2d008e",
        "primary-container": "#a491ff",
        "outline-variant": "#46484f",
        "surface-container-high": "#1d1f27",
        "surface-container-low": "#11131a",
        secondary: "#1fc0fe",
        "on-surface": "#e5e4ed",
        "secondary-container": "#006689",
        "tertiary-container": "#fc84b7",
        "inverse-surface": "#faf8ff",
        background: "#0c0e14",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Manrope"],
        label: ["Inter"],
      },
    },
  },
  plugins: [],
}
