// src/config/blockchain.js
// Loads deployed contract addresses from local.json (local) or env vars (testnet/mainnet)

const path = require('path');
const fs   = require('fs');

const IS_LOCAL = (process.env.BLOCKCHAIN_NETWORK || 'local') === 'local';

let _addresses = null;

function getAddresses() {
  if (_addresses) return _addresses;

  if (IS_LOCAL) {
    // Read from contracts/addresses/local.json (generated by deploy script)
    const localJsonPath = path.join(
      __dirname,
      '../../../land-registry-contracts/contracts/addresses/local.json'
    );

    if (!fs.existsSync(localJsonPath)) {
      throw new Error(
        `Local contract addresses not found at ${localJsonPath}.\n` +
        'Run: cd land-registry-contracts && npx hardhat run scripts/deploy.js'
      );
    }

    _addresses = JSON.parse(fs.readFileSync(localJsonPath, 'utf8'));
  } else {
    // Use env vars for testnet / mainnet
    _addresses = {
      LandRegistry:     process.env.LAND_REGISTRY_ADDRESS,
      MultiSigTransfer: process.env.MULTI_SIG_TRANSFER_ADDRESS,
      OfficerMultiSig:  process.env.OFFICER_MULTI_SIG_ADDRESS,
    };
  }

  return _addresses;
}

function getArtifact(contractName) {
  const artifactPath = path.join(
    __dirname,
    '../../../land-registry-contracts/artifacts/contracts',
    `${contractName}.sol`,
    `${contractName}.json`
  );

  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `Artifact not found for ${contractName} at ${artifactPath}.\n` +
      'Run: cd land-registry-contracts && npx hardhat compile'
    );
  }

  return JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
}

module.exports = { getAddresses, getArtifact, IS_LOCAL };